name: Download Mods

on:
  workflow_dispatch:
    inputs:
      file_name:
        description: "Filename to save the downloaded file as (example: strava-437.11-signed.apk)"
        required: true
        type: string
      download_url:
        description: "URL to download the APK from"
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4

      - name: Generate tag and release name
        run: |
          TAG="build-${{ github.run_number }}"
          NAME="Strava-Signed-${TAG}-$(date +%s)"
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "RELEASE_NAME=$NAME" >> $GITHUB_ENV

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y wget zip

      - name: Download file
        run: |
          wget -O "${{ inputs.file_name }}" "${{ inputs.download_url }}"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG }}
          release_name: ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: false

      - name: Upload to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ inputs.file_name }}
          tag: ${{ env.TAG }}
          overwrite: true
