name: Download APK and Put on Release
on:
  workflow_dispatch:
jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt install -y curl wget unzip zip

      - name: Download APK
        run: |
          sudo wget "https://www.dropbox.com/scl/fi/x1h1ffcme4ocettxbjnq2/braveXt.apk?rlkey=zdb94ol6i3acign5vh4zwyw5c&st=7ashbfnb&dl=1"
          sudo wget "https://www.dropbox.com/scl/fi/a07u531jogialowmev4e7/chromiumXt.apk?rlkey=swpg9fgjw3w3d04nl3dmk9j9a&st=vd92cgei&dl=1"
          ls -a
          tree ./
          mv "chromiumXt.apk" chromium-signed.apk
          mv "braveXt.apk" brave-signed.apk

      - name: Upload to Release
        uses: svenstaro/upload-release-action@v2
        with:
          body: add chromium-signed.apk
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./chromium-signed.apk
          release_name: APK Release
          tag: 1.0.0
          file_glob: true
          overwrite: true
