name: Download APK and Put on Release

on:
  workflow_dispatch:

jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt install -y curl wget unzip zip

      - name: Checkout
        uses: actions/checkout@v4

      - name: Read .TOML
        uses: SebRollen/toml-action@v1.2.0
        id: read_app
        with:
          file: 'files.toml'
          field: 'app'

      - name: Download APK
        run: |
          sudo wget ${{steps.read_app.outputs.url}}${{steps.read_app.outputs.chromium.url}}
          ls -a
          tree ./
          mv "{{steps.read_app.outputs.chromium.url}}" chromium-signed.apk

      - name: Upload to Release
        uses: svenstaro/upload-release-action@v2
        with:
          body: add chromium signed.apk
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./chromium-signed.apk
          release_name: APK Release
          tag: 1.0.0
          file_glob: true
          overwrite: true
