name: Download APK and Put on Release
on:
  workflow_dispatch:
jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt install -y curl wget unzip zip

      - name: Download APK
        run: |
          sudo wget "https://www.dropbox.com/scl/fi/x1h1ffcme4ocettxbjnq2/braveXt.apk?rlkey=zdb94ol6i3acign5vh4zwyw5c&st=7ashbfnb&dl=1"
          sudo wget "https://www.dropbox.com/scl/fi/sdzgirpb2bb54inl6tnb3/kiwi-armv7.apk?rlkey=5895x5h2hl6i0sdjb3s9i8ju1&st=79ia9c19&dl=1"
          sudo wget "https://www.dropbox.com/scl/fi/1cbfeg92zget2jtk3yoik/kiwi-arm64.apk?rlkey=c6th9g9d8nlb8nupvzctu8rfv&st=7nxkfdvb&dl=1"
          sudo wget "https://www.dropbox.com/scl/fi/5pa6opthz30yi5g3bhym9/edge-armv7.apk?rlkey=923iflpa04jh18nwiwqs89urs&st=2gs7ln79&dl=1"
          sudo wget "https://www.dropbox.com/scl/fi/g9wc00gnk0gw0nmkatwnf/edge-arm64.apk?rlkey=5odw02lncw5tmxtyb4todgy77&st=2zqpx37t&dl=1"
          sudo wget "https://www.dropbox.com/scl/fi/a07u531jogialowmev4e7/chromiumXt.apk?rlkey=swpg9fgjw3w3d04nl3dmk9j9a&st=vd92cgei&dl=1"
          tree ./
          mv "chromiumXt.apk?rlkey=swpg9fgjw3w3d04nl3dmk9j9a&st=vd92cgei&dl=1" chromium-signed.apk
          mv "braveXt.apk?rlkey=zdb94ol6i3acign5vh4zwyw5c&st=7ashbfnb&dl=1" brave-signed.apk
          mv "edge-armv7.apk?rlkey=923iflpa04jh18nwiwqs89urs&st=2gs7ln79&dl=1" edge-signed-armv7.apk
          mv "edge-arm64.apk?rlkey=5odw02lncw5tmxtyb4todgy77&st=2zqpx37t&dl=1" edge-signed-arm64.apk
          mv "kiwi-armv7.apk?rlkey=5895x5h2hl6i0sdjb3s9i8ju1&st=79ia9c19&dl=1' kiwi-signed-armv7.apk
          mv "kiwi-arm64.apk?rlkey=c6th9g9d8nlb8nupvzctu8rfv&st=7nxkfdvb&dl=1" kiwi-signed-arm64.apk

      - name: Upload to Release
        uses: svenstaro/upload-release-action@v2
        with:
          body: |
              __Added More ChromeXt Build__

              Chromium _`v131.0.6725.0`_
              Brave _`v1.61.121`_
              Edge _`v128.0.2739.82`_
              Kiwi _`v124.0.6327.4`_

              > __FEATURES__
              >  ErudaConsole
              >  UserScripts

              > __userScripts Panel :__
              _https://jingmatrix.github.io/ChromeXt/_
              > __userScript Download :__
              _https://greasyfork.org/_
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./*.apk
          release_name: APK Release
          tag: 1.0.3
          file_glob: true
          overwrite: true
