name: Download Strava and Put on Release

on:
  workflow_dispatch:

jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y curl wget zip tree || true

      - name: Download APK with Proper Name
        run: |
          wget -O strava-416.14-signed.apk "https://www.dropbox.com/scl/fi/2s3wls4m60uv6ic13mntw/strava_v416.14_modded.xapk?rlkey=w5jehyzke07519redkzjv6c4r&st=ifsba1hf&dl=1"
          tree . || true

      - name: Upload to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: strava-416.14-signed.apk
          asset_name: strava-416.14-signed.apk
          tag: 1.0.5
          release_name: APK Release
          body: |
            __Strava v416.14 Premium__

            > __FEATURES__
            > Premium Features, Routes, Replay, Matched Run, Segment Efforts, Map Style
            > Remove Subscription Suggestion
          overwrite: true
          
