name: Download APK and Put on Release
on:
  workflow_dispatch:
jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt install -y curl wget unzip zip

      - name: Download APK
        run: |
          sudo wget {{app.url}}{{app.chromium.url}}
          ls -a
          tree ./
          mv "{{app.chromium.url}}" chromium-signed.apk

      - name: Upload to Release
        uses: svenstaro/upload-release-action@v2
        with:
          body: add chromium signed.apk
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./chromium-signed.apk
          release_name: APK Release
          tag: 1.0.0
          file_glob: true
          overwrite: true
